Added: 1 file, 2 images, and initial styleing for the login page of the Tracker app.
turingschool/tracker-crm-fe pull request #16
Opened 2024-12-07 04:26 UTC by DRIF7ER

## Type of Change
- [x] styling 🎨

## Description

- Added: small Turing logo png, large Turing photo png
- Added: 'react-app-env.d.ts' file to allow for image imports without TS throwing an error.
- Changed: 'index.html' file to display tab icon logo
- Edited: App.tsx file, Login.tsx file

## Motivation and Context

Styling login page was a requirement of the project and to enhance the UI of the app overall.

## Related Tickets

closes #2 

## Screenshots (if appropriate):
![Initial Login Page](https://github.com/user-attachments/assets/4aca0b9e-3663-4782-89be-cf910cdd0db9)

## Added Test?

- [x] No 🙅

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-12-07 17:51 UTC, jphill19 requested changes
I noticed there aren’t any Cypress tests for the login page to verify that everything is displaying as expected. Additionally, when I tried to fetch and check out your branch, I encountered a TypeScript error, which prevented the login screen from rendering.

2024-12-08 00:43 UTC, DRIF7ER commented
Hey thanks!
    To be honest I hadn't thought about the artistic license so that may need to be a question for Erin (better to ask for forgiveness?).
     Unsure about the README as well. I figure we'll prolly get a dev specific login to work on stuff but as far as I know there isn't one yet. Alternatively you could set the loggedin state (in App.tsx) to true in order to access everything else while you're on your machine just don't forget to set if back to false when you push up.

2024-12-09 20:35 UTC, ROlearyPro requested changes
I think you've overall made good changes, though I'd make sure that the register button actually can link to somewhere else, rather than getting the same result as the login button. Also, as I noted in the code reviews, you might want to make sure you can account for mobile users more thoroughly?

2024-12-09 20:35 UTC, ROlearyPro commented on cypress/e2e/LoginSpec.cy.js
Seems good so far, though as you mention we'll probably have to refactor the actual login tests once that's working.

2024-12-09 20:35 UTC, ROlearyPro commented on src/App.tsx
Deleting this stuff outright rather than just commenting it out might be better.

2024-12-09 20:35 UTC, ROlearyPro commented on src/Login.tsx
Great work and styling! I love the color bar, and the layout is nice. I do wonder if you might want to rework things to account for mobile?

2024-12-10 23:22 UTC, jphill19 commented on public/index.html
> +    <link rel="icon" href="./Turing-logo-small.png" />
clean change, this is nice. May be best to place all of images inside a public folder, but this works

2024-12-10 23:25 UTC, jphill19 reviewed
I like that you added test, nice job Charles!

2024-12-10 23:28 UTC, merged